import type { Metadata } from 'next';
import styles from './auth.module.css';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={styles.outerContainer}>
                <div>
                    {children}
                </div>
            </body>
        </html>
    );
}
