import type { Metadata } from 'next';
import '../globals.css';
import Providers from '@/providers';
import { AppHeader } from '@/components/navigation/AppHeader/AppHeader';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <AppHeader />
          {children}
        </Providers>
      </body>
    </html>
  );
}
